-- TEMPORARY, AUTOGENERATED

USE my_store;

-- Sample data for `customers`
INSERT INTO customers (name, email, phone) VALUES
('Alice Wonderland', 'alice.w@example.com', '123-456-7890'),
('Bob The Builder', 'bob.b@example.com', '098-765-4321'),
('Charlie Chaplin', 'charlie.c@example.com', '111-222-3333'),
('Diana Prince', 'diana.p@example.com', '444-555-6666'),
('Eve Harrington', 'eve.h@example.com', '777-888-9999');

-- Sample data for `address_types`
INSERT INTO address_types (type_name) VALUES
('Shipping'),
('Billing'),
('Home'),
('Work');

-- Sample data for `customer_addresses`
INSERT INTO customer_addresses (customer_id, country, state, city, street, floor, appartment_no, address_type_id, is_default) VALUES
(1, 'USA', 'California', 'Los Angeles', '123 Hollywood Blvd', NULL, '10A', 1, 1),
(1, 'USA', 'California', 'Los Angeles', '123 Hollywood Blvd', NULL, '10A', 2, 0),
(2, 'Canada', 'Ontario', 'Toronto', '45 Yonge St', '5', '500', 1, 1),
(3, 'UK', 'England', 'London', '10 Downing St', NULL, NULL, 1, 1),
(4, 'Germany', 'Bavaria', 'Munich', '789 Oktoberfest Str', NULL, 'Unit 3', 1, 1),
(5, 'France', 'Ile-de-France', 'Paris', '1 Rue de la Paix', '2', 'B', 2, 1);

-- Sample data for `product_categories`
INSERT INTO product_categories (name, parent_category_id) VALUES
('Electronics', NULL),
('Books', NULL),
('Clothing', NULL),
('Laptops', 1),
('Smartphones', 1),
('Fiction', 2),
('Non-Fiction', 2),
('Menswear', 3),
('Womenswear', 3),
('Accessories', 3);

-- Sample data for `products`
INSERT INTO products (name, description, price) VALUES
('MacBook Air M2', 'Sleek and powerful laptop from Apple.', 1199.99),
('iPhone 15 Pro', 'Latest smartphone with advanced camera.', 999.00),
('The Great Gatsby', 'Classic American novel by F. Scott Fitzgerald.', 12.50),
('Dune', 'Epic science fiction novel by Frank Herbert.', 15.75),
('Mens T-Shirt', 'Comfortable cotton t-shirt for men.', 25.00),
('Womens Jeans', 'Stylish denim jeans for women.', 55.99),
('Wireless Headphones', 'Noise-cancelling headphones with long battery life.', 199.99);

-- Sample data for `product_to_categories`
INSERT INTO product_to_categories (product_id, category_id) VALUES
(1, 1), -- MacBook Air M2 -> Electronics
(1, 4), -- MacBook Air M2 -> Laptops
(2, 1), -- iPhone 15 Pro -> Electronics
(2, 5), -- iPhone 15 Pro -> Smartphones
(3, 2), -- The Great Gatsby -> Books
(3, 6), -- The Great Gatsby -> Fiction
(4, 2), -- Dune -> Books
(4, 6), -- Dune -> Fiction
(5, 3), -- Mens T-Shirt -> Clothing
(5, 8), -- Mens T-Shirt -> Menswear
(6, 3), -- Womens Jeans -> Clothing
(6, 9), -- Womens Jeans -> Womenswear
(7, 1), -- Wireless Headphones -> Electronics
(7, 10); -- Wireless Headphones -> Accessories

-- Sample data for `product_variants`
INSERT INTO product_variants (product_id, sku, unit_price, quantity_in_stock) VALUES
(1, 'MBA-M2-256GB', 1199.99, 50),
(1, 'MBA-M2-512GB', 1399.99, 30),
(2, 'IP15P-128GB-BL', 999.00, 100),
(2, 'IP15P-256GB-WH', 1099.00, 75),
(5, 'TSHIRT-M-BLK', 25.00, 200),
(5, 'TSHIRT-L-WHT', 25.00, 150),
(6, 'JEANS-S-BLUE', 55.99, 80),
(6, 'JEANS-M-BLACK', 55.99, 60),
(7, 'WH-ANC-BLK', 199.99, 120);

-- Sample data for `variant_options`
INSERT INTO variant_options (name) VALUES
('Color'),
('Storage'),
('Size');

-- Sample data for `variant_option_values`
INSERT INTO variant_option_values (option_id, value) VALUES
(1, 'Space Gray'), -- Color
(1, 'Silver'),     -- Color
(1, 'Midnight'),   -- Color
(1, 'Black'),      -- Color
(1, 'White'),      -- Color
(1, 'Blue'),       -- Color
(2, '128GB'),      -- Storage
(2, '256GB'),      -- Storage
(2, '512GB'),      -- Storage
(3, 'Small'),      -- Size
(3, 'Medium'),     -- Size
(3, 'Large'),      -- Size
(3, 'X-Large');    -- Size

-- Sample data for `variant_option_assignments`
INSERT INTO variant_option_assignments (variant_id, value_id) VALUES
-- MacBook Air M2 variants
(1, 9), -- MBA-M2-256GB -> 256GB (Storage)
(1, 1), -- MBA-M2-256GB -> Space Gray (Color)
(2, 9), -- MBA-M2-512GB -> 512GB (Storage)
(2, 2), -- MBA-M2-512GB -> Silver (Color)

-- iPhone 15 Pro variants
(3, 7), -- IP15P-128GB-BL -> 128GB (Storage)
(3, 4), -- IP15P-128GB-BL -> Black (Color)
(4, 8), -- IP15P-256GB-WH -> 256GB (Storage)
(4, 5), -- IP15P-256GB-WH -> White (Color)

-- Mens T-Shirt variants
(5, 11), -- TSHIRT-M-BLK -> Medium (Size)
(5, 4),  -- TSHIRT-M-BLK -> Black (Color)
(6, 12), -- TSHIRT-L-WHT -> Large (Size)
(6, 5),  -- TSHIRT-L-WHT -> White (Color)

-- Womens Jeans variants
(7, 10), -- JEANS-S-BLUE -> Small (Size)
(7, 6),  -- JEANS-S-BLUE -> Blue (Color)
(8, 11), -- JEANS-M-BLACK -> Medium (Size)
(8, 4),  -- JEANS-M-BLACK -> Black (Color)

-- Wireless Headphones variant
(9, 4);  -- WH-ANC-BLK -> Black (Color)